const Breeds = [
  {
    id: 1,
    name: "Labrador Retriever",
    imagePatch: "labrador retriever.png",
    description: "Przyjazny, rodzinny pies o dużej energii.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 2,
    name: "Golden Retriever",
    imagePatch: "golden retriever.png",
    description: "Inteligentny, przyjazny pies idealny dla rodzin.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 3,
    name: "Poodle",
    imagePatch: "poodle.png",
    description: "Hipoalergiczny pies o dużej inteligencji.",
    requiredAttention: "MEDIUM",
    activityLevel: "MEDIUM",
    independenceLevel: "MEDIUM",
    isAllergenic: true,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 4,
    name: "German Shepherd",
    imagePatch: "German Shepherd.png",
    description: "Lojalny, inteligentny pies pracujący.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 5,
    name: "Bulldog",
    imagePatch: "bulldog.png",
    description: "Spokojny i przyjazny pies o niskiej aktywności.",
    requiredAttention: "LOW",
    activityLevel: "LOW",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 6,
    name: "Beagle",
    imagePatch: "beagle.png",
    description: "Wesoły, ciekawski pies o dużej energii.",
    requiredAttention: "MEDIUM",
    activityLevel: "HIGH",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 7,
    name: "Dachshund",
    imagePatch: "dachshund.png",
    description: "Niezależny, ale przyjazny pies myśliwski.",
    requiredAttention: "MEDIUM",
    activityLevel: "MEDIUM",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 8,
    name: "Siberian Husky",
    imagePatch: "siberian husky.png",
    description: "Niezależny pies o wysokiej energii, wymagający aktywności.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 9,
    name: "Shih Tzu",
    imagePatch: "Shich Tzu.png",
    description: "Towarzyski, spokojny pies rodzinny.",
    requiredAttention: "LOW",
    activityLevel: "LOW",
    independenceLevel: "MEDIUM",
    isAllergenic: true,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 10,
    name: "Border Collie",
    imagePatch: "border collie.png",
    description: "Bardzo inteligentny, pracowity pies pasterski.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 11,
    name: "Boxer",
    imagePatch: "boxer dog.png",
    description: "Energiczny, lojalny i przyjazny pies.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 12,
    name: "Chihuahua",
    imagePatch: "chihuahua.png",
    description: "Mały, odważny i bardzo przywiązany do właściciela.",
    requiredAttention: "LOW",
    activityLevel: "MEDIUM",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 13,
    name: "Cavalier King Charles Spaniel",
    imagePatch: "Cavalier King Charles Spaniel.png",
    description: "Spokojny, towarzyski pies rodzinny.",
    requiredAttention: "MEDIUM",
    activityLevel: "LOW",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 14,
    name: "Dalmatian",
    imagePatch: "dalmatian.png",
    description: "Energiczny pies wymagający dużo ruchu.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 15,
    name: "Doberman",
    imagePatch: "Doberman.png",
    description: "Inteligentny, czujny pies stróżujący.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 16,
    name: "Great Dane",
    imagePatch: "Great Dane.png",
    description: "Gigantyczny, ale łagodny pies rodzinny.",
    requiredAttention: "HIGH",
    activityLevel: "LOW",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 17,
    name: "Cocker Spaniel",
    imagePatch: "Cocker Spaniel.png",
    description: "Przyjazny pies myśliwski o średniej aktywności.",
    requiredAttention: "MEDIUM",
    activityLevel: "MEDIUM",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 18,
    name: "Rottweiler",
    imagePatch: "Rottweiler.png",
    description: "Silny, pewny siebie pies stróżujący.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 19,
    name: "Maltese",
    imagePatch: "Maltese dog.png",
    description: "Mały, delikatny pies towarzyski.",
    requiredAttention: "LOW",
    activityLevel: "LOW",
    independenceLevel: "HIGH",
    isAllergenic: true,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 20,
    name: "Papillon",
    imagePatch: "papillon dog.png",
    description: "Inteligentny, energiczny piesek do towarzystwa.",
    requiredAttention: "MEDIUM",
    activityLevel: "MEDIUM",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 21,
    name: "French Bulldog",
    imagePatch: "French Bulldog.png",
    description: "Przyjazny, mało aktywny pies rodzinny.",
    requiredAttention: "LOW",
    activityLevel: "LOW",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 22,
    name: "Akita Inu",
    imagePatch: "fakita inu.png",
    description: "Niezależny, lojalny pies stróżujący.",
    requiredAttention: "HIGH",
    activityLevel: "MEDIUM",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 23,
    name: "Samoyed",
    imagePatch: "Samoyed dog.png",
    description: "Towarzyski, energiczny pies zaprzęgowy.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 24,
    name: "Weimaraner",
    imagePatch: "Weimaraner dog.png",
    description: "Inteligentny, aktywny pies myśliwski.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 25,
    name: "Australian Shepherd",
    imagePatch: "Australian Shepherd.png",
    description: "Bardzo inteligentny i energiczny pies pasterski.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 26,
    name: "Bichon Frise",
    imagePatch: "Bichon Frise.png",
    description: "Hipoalergiczny piesek do towarzystwa.",
    requiredAttention: "MEDIUM",
    activityLevel: "LOW",
    independenceLevel: "HIGH",
    isAllergenic: true,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 27,
    name: "Whippet",
    imagePatch: "Whippet.png",
    description: "Szybki, spokojny pies o łagodnym charakterze.",
    requiredAttention: "MEDIUM",
    activityLevel: "HIGH",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 28,
    name: "Pug",
    imagePatch: "Pug.png",
    description: "Zabawny, mało aktywny pies rodzinny.",
    requiredAttention: "LOW",
    activityLevel: "LOW",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: true,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 29,
    name: "Shiba Inu",
    imagePatch: "Shiba Inu.png",
    description: "Niezależny, czysty i inteligentny pies.",
    requiredAttention: "MEDIUM",
    activityLevel: "HIGH",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
  {
    id: 30,
    name: "Bernese Mountain Dog",
    imagePatch: "Bernese Mountain Dog.png",
    description: "Spokojny, lojalny pies rodzinny.",
    requiredAttention: "HIGH",
    activityLevel: "LOW",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 31,
    name: "Newfoundland",
    imagePatch: "Newfoundland dog.png",
    description: "Gigantyczny, łagodny pies ratowniczy.",
    requiredAttention: "HIGH",
    activityLevel: "LOW",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 32,
    name: "Saint Bernard",
    imagePatch: "Saint Bernard.png",
    description: "Łagodny, czuły olbrzym.",
    requiredAttention: "HIGH",
    activityLevel: "LOW",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 33,
    name: "Irish Setter",
    imagePatch: "Irish Setter.png",
    description: "Energiczny, wesoły pies myśliwski.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "LOW",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 34,
    name: "Alaskan Malamute",
    imagePatch: "Alaskan Malamute.png",
    description: "Silny pies zaprzęgowy wymagający aktywności.",
    requiredAttention: "HIGH",
    activityLevel: "HIGH",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "LARGE",
  },
  {
    id: 35,
    name: "Basenji",
    imagePatch: "Basenji dog.png",
    description: "Niezależny, cichy pies bez szczekania.",
    requiredAttention: "LOW",
    activityLevel: "MEDIUM",
    independenceLevel: "HIGH",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "SMALL",
  },
  {
    id: 36,
    name: "Bull Terrier",
    imagePatch: "Bull Terrier.png",
    description: "Silny, energiczny pies towarzyski.",
    requiredAttention: "MEDIUM",
    activityLevel: "HIGH",
    independenceLevel: "MEDIUM",
    isAllergenic: false,
    isGoodWithKids: true,
    isGoodWithDogs: true,
    isGoodWithCats: false,
    isGoodWithOtherAnimals: true,
    size: "MEDIUM",
  },
];

export default Breeds;
