const images = {
  "labrador retriever.png": require("../assets/pictures/labrador retriever.png"),
  "golden retriever.png": require("../assets/pictures/golden retriever.png"),
  "poodle.png": require("../assets/pictures/poodle.png"),
  "German Shepherd.png": require("../assets/pictures/German Shepherd.png"),
  "bulldog.png": require("../assets/pictures/bulldog.png"),
  "beagle.png": require("../assets/pictures/beagle.png"),
  "dachshund.png": require("../assets/pictures/dachshund.png"),
  "siberian husky.png": require("../assets/pictures/siberian husky.png"),
  "Shich Tzu.png": require("../assets/pictures/Shich Tzu.png"),
  "border collie.png": require("../assets/pictures/border collie.png"),
  "boxer dog.png": require("../assets/pictures/boxer dog.png"),
  "chihuahua.png": require("../assets/pictures/chihuahua.png"),
  "Cavalier King Charles Spaniel.png": require("../assets/pictures/Cavalier King Charles Spaniel.png"),
  "dalmatian.png": require("../assets/pictures/dalmatian.png"),
  "Doberman.png": require("../assets/pictures/Doberman.png"),
  "Great Dane.png": require("../assets/pictures/Great Dane.png"),
  "Cocker Spaniel.png": require("../assets/pictures/Cocker Spaniel.png"),
  "Rottweiler.png": require("../assets/pictures/Rottweiler.png"),
  "Maltese dog.png": require("../assets/pictures/Maltese dog.png"),
  "papillon dog.png": require("../assets/pictures/papillon dog.png"),
  "French Bulldog.png": require("../assets/pictures/French Bulldog.png"),
  "fakita inu.png": require("../assets/pictures/fakita inu.png"),
  "Samoyed dog.png": require("../assets/pictures/Samoyed dog.png"),
  "Weimaraner dog.png": require("../assets/pictures/Weimaraner dog.png"),
  "Australian Shepherd.png": require("../assets/pictures/Australian Shepherd.png"),
  "Bichon Frise.png": require("../assets/pictures/Bichon Frise.png"),
  "Whippet.png": require("../assets/pictures/Whippet.png"),
  "Pug.png": require("../assets/pictures/Pug.png"),
  "Shiba Inu.png": require("../assets/pictures/Shiba Inu.png"),
  "Bernese Mountain Dog.png": require("../assets/pictures/Bernese Mountain Dog.png"),
  "Newfoundland dog.png": require("../assets/pictures/Newfoundland dog.png"),
  "Saint Bernard.png": require("../assets/pictures/Saint Bernard.png"),
  "Irish Setter.png": require("../assets/pictures/Irish Setter.png"),
  "Alaskan Malamute.png": require("../assets/pictures/Alaskan Malamute.png"),
  "Basenji dog.png": require("../assets/pictures/Basenji dog.png"),
  "Bull Terrier.png": require("../assets/pictures/Bull Terrier.png"),
};

export const getImageSource = (imagePath) => images[imagePath] || null;
